name: Generate and Post Water Report

on:
  schedule:
    - cron: '0 2 * * *' # ทุกวัน 09:00 เวลาไทย
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
      MAKE_WEBHOOK_URL: ${{ secrets.MAKE_WEBHOOK_URL }}
      
      # เพิ่มค่า LINE Secrets เพื่อให้ main.py ดึงไปใช้ได้
      LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
      LINE_TARGET_ID: ${{ secrets.LINE_TARGET_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      # เพิ่มขั้นตอนการ Cache เพื่อความเร็วและป้องกัน Timeout
      - name: Cache WebDriver
        uses: actions/cache@v4
        with:
          path: ~/.wdm
          key: ${{ runner.os }}-webdriver-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-webdriver-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate image and status text
        run: python main.py

      - name: Send Report to Make.com
        run: |
          STATUS_TEXT=$(cat status.txt)
          curl -X POST -F "file=@final_report.jpg" -F "status=$STATUS_TEXT" ${{ env.MAKE_WEBHOOK_URL }}
