name: Generate and Post Water Report

on:
  schedule:
    - cron: '0 2 * * *'  # ทุกวัน 09:00 เวลาไทย
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FB_PAGE_TOKEN: ${{ secrets.FB_PAGE_TOKEN }}
      FB_PAGE_ID: ${{ secrets.FB_PAGE_ID }}
      OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}

    steps:
      - name: Send final image to Make Webhook
        run: |
          curl -X POST -F "file=@final_report.jpg" https://hook.eu2.make.com/bux1lm098yc1e1hij8u7nbly92eag22o

    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Generate image
      run: python main.py

    - name: Post to Facebook
      run: python post_to_facebook.py
