name: Generate Water Report

on:
  schedule:
    - cron: '0 2 * * *'
    - cron: '0 5 * * *'
    - cron: '0 9 * * *'
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
      MAKE_WEBHOOK_URL: ${{ secrets.MAKE_WEBHOOK_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run main script
        run: python main.py

      - name: Load caption from status.txt
        run: |
          echo "STATUS_TEXT=$(cat status.txt | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Post to Facebook
        run: |
          curl -X POST -F "file=@final_report.jpg" -F "status=$STATUS_TEXT" $MAKE_WEBHOOK_URL
