name: Generate Water Report Image

on:
  schedule:
    - cron: '0 */4 * * *'  # ทุก 4 ชั่วโมง
  workflow_dispatch:       # รันด้วยมือได้ด้วย

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 🔧 Install dependencies
        run: |
          pip install -r requirements.txt

      - name: 🔐 Set up environment variables
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        run: echo "Environment variables loaded"

      - name: 🎨 Generate final_report.jpg
        run: python main.py

      - name: 📤 Commit and Push updated image
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git pull origin main  # หรือ gh-pages ถ้าคุณใช้ branch นั้น
          git add final_report.jpg
          git commit -m "🔁 Auto-update final_report.jpg" || echo "No changes to commit"
          git push origin main  # เปลี่ยนเป็น gh-pages ถ้าใช้ branch นั้น
