name: Generate Water Report

on:
  schedule:
    - cron: '0 2 * * *'  # เวลาไทย 09:00 น.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run script to generate image
      run: python main.py
