name: Generate and Post Water Report

on:
  schedule:
    - cron: '0 1 * * *'   # 08:00 ICT
    - cron: '0 5 * * *'   # 12:00 ICT
    - cron: '0 11 * * *'  # 18:00 ICT
    - cron: '30 13 * * *' # 20:30 ICT
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
      MAKE_WEBHOOK_URL: ${{ secrets.MAKE_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run script
        run: python main.py
      - name: Read caption text from script output
        id: caption
        run: echo "STATUS_TEXT=$(cat status.txt)" >> $GITHUB_ENV
      - name: Post to Facebook via Webhook
        run: |
          curl -X POST -F "file=@final_report.jpg" -F "status=$STATUS_TEXT" ${{ secrets.MAKE_WEBHOOK_URL }}
