name: water-report

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2,5,8,11 * * *'  # ทำงานวันละ 4 รอบ ตามเวลาประเทศไทย (UTC+7 → UTC-7)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run main script
        run: python main.py
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
          MAKE_WEBHOOK_URL: ${{ secrets.MAKE_WEBHOOK_URL }}

      - name: Read caption from status.txt
        run: |
          echo "STATUS_TEXT<<EOF" >> $GITHUB_ENV
          cat status.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Send to Make Webhook
        run: |
          curl -X POST "${{ secrets.MAKE_WEBHOOK_URL }}" \
            -H "Content-Type: application/json" \
            -d @<(jq -n --arg caption "$STATUS_TEXT" --argfile image final_report.jpg '{
              caption: $caption,
              image: "data:image/jpeg;base64," + ($image | @base64)
            }')
